/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emploi.du.temps;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MIDOU
 */
public class theMain extends javax.swing.JFrame {
     public static Connection connection;
    /**
     * Creates new form theMain
     */
    public theMain() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajout_enseignant = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_enseignant = new javax.swing.JTextField();
        prenom_enseignant = new javax.swing.JTextField();
        matiere_selection = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        ajout_classe = new javax.swing.JDialog();
        Nom_classe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Niveau = new javax.swing.JComboBox<>();
        specialité = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        ajout_salle = new javax.swing.JDialog();
        Num_salle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        designation_salle = new javax.swing.JTextField();
        theCard = new javax.swing.JPanel();
        liste_enseignants = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_enseignant = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        liste_matiere = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_matiere = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        liste_classes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_classe = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        liste_salles = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_salle = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        liste_enseignant_bouton = new javax.swing.JButton();
        Exit_button = new javax.swing.JButton();
        liste_matieres_bouton = new javax.swing.JButton();
        liste_classes_bouton = new javax.swing.JButton();
        liste_salles_bouton = new javax.swing.JButton();
        affecter_prof_classe = new javax.swing.JButton();
        generer_emploi_du_temps = new javax.swing.JButton();

        ajout_enseignant.setAlwaysOnTop(true);
        ajout_enseignant.setLocation(new java.awt.Point(0, 0));
        ajout_enseignant.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        Nom_enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_enseignantActionPerformed(evt);
            }
        });

        jLabel3.setText("matiere");

        jButton12.setText("ajouter");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("annuler");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajout_enseignantLayout = new javax.swing.GroupLayout(ajout_enseignant.getContentPane());
        ajout_enseignant.getContentPane().setLayout(ajout_enseignantLayout);
        ajout_enseignantLayout.setHorizontalGroup(
            ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_enseignantLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ajout_enseignantLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jButton13))
                    .addGroup(ajout_enseignantLayout.createSequentialGroup()
                        .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(57, 57, 57)
                        .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(matiere_selection, 0, 152, Short.MAX_VALUE)
                            .addComponent(Nom_enseignant)
                            .addComponent(prenom_enseignant))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        ajout_enseignantLayout.setVerticalGroup(
            ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_enseignantLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nom_enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenom_enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matiere_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(ajout_enseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(21, 21, 21))
        );

        ajout_enseignant.setLocationRelativeTo(liste_enseignants );

        ajout_classe.setAlwaysOnTop(true);
        ajout_classe.setSize(new java.awt.Dimension(400, 300));

        jLabel4.setText("nom de classe");

        jLabel5.setText("specialité");

        jLabel6.setText("niveau");

        Niveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        Niveau.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NiveauItemStateChanged(evt);
            }
        });

        specialité.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "science", "lettres" }));
        specialité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialitéActionPerformed(evt);
            }
        });

        jButton14.setText("ajouter");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("annuler");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajout_classeLayout = new javax.swing.GroupLayout(ajout_classe.getContentPane());
        ajout_classe.getContentPane().setLayout(ajout_classeLayout);
        ajout_classeLayout.setHorizontalGroup(
            ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_classeLayout.createSequentialGroup()
                .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajout_classeLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton14)
                        .addGap(80, 80, 80)
                        .addComponent(jButton15))
                    .addGroup(ajout_classeLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specialité, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nom_classe)
                            .addComponent(Niveau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        ajout_classeLayout.setVerticalGroup(
            ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_classeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nom_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(specialité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(ajout_classeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(24, 24, 24))
        );

        ajout_classe.setLocationRelativeTo(liste_classes );

        ajout_salle.setAlwaysOnTop(true);
        ajout_salle.setSize(new java.awt.Dimension(400, 300));

        jLabel7.setText("num de salle");

        jLabel9.setText("designation");

        jButton19.setText("ajouter");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("annuler");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajout_salleLayout = new javax.swing.GroupLayout(ajout_salle.getContentPane());
        ajout_salle.getContentPane().setLayout(ajout_salleLayout);
        ajout_salleLayout.setHorizontalGroup(
            ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_salleLayout.createSequentialGroup()
                .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajout_salleLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Num_salle)
                            .addComponent(designation_salle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ajout_salleLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton19)
                        .addGap(80, 80, 80)
                        .addComponent(jButton20)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        ajout_salleLayout.setVerticalGroup(
            ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_salleLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(designation_salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(ajout_salleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addGap(46, 46, 46))
        );

        ajout_salle.setLocationRelativeTo(liste_salles );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        theCard.setPreferredSize(new java.awt.Dimension(500, 403));
        theCard.setLayout(new java.awt.CardLayout());

        table_enseignant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_enseignantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_enseignant);

        jButton3.setText("ajouter");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("modifier");
        jButton4.setEnabled(false);

        jButton5.setText("supprimer");
        jButton5.setEnabled(false);

        javax.swing.GroupLayout liste_enseignantsLayout = new javax.swing.GroupLayout(liste_enseignants);
        liste_enseignants.setLayout(liste_enseignantsLayout);
        liste_enseignantsLayout.setHorizontalGroup(
            liste_enseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_enseignantsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(liste_enseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(liste_enseignantsLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        liste_enseignantsLayout.setVerticalGroup(
            liste_enseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_enseignantsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(liste_enseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        theCard.add(liste_enseignants, "card_enseignant");

        liste_matiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liste_matiereMouseClicked(evt);
            }
        });

        table_matiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_matiereMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_matiere);

        jButton6.setText("ajouter");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("modifier");
        jButton7.setEnabled(false);

        jButton8.setText("supprimer");
        jButton8.setEnabled(false);

        javax.swing.GroupLayout liste_matiereLayout = new javax.swing.GroupLayout(liste_matiere);
        liste_matiere.setLayout(liste_matiereLayout);
        liste_matiereLayout.setHorizontalGroup(
            liste_matiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_matiereLayout.createSequentialGroup()
                .addGroup(liste_matiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(liste_matiereLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(liste_matiereLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addGap(20, 20, 20))
        );
        liste_matiereLayout.setVerticalGroup(
            liste_matiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_matiereLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(liste_matiereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        theCard.add(liste_matiere, "card_matiere");

        liste_classes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liste_classesMouseClicked(evt);
            }
        });

        table_classe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_classeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_classe);

        jButton9.setText("ajouter");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("modifier");
        jButton10.setEnabled(false);

        jButton11.setText("supprimer");
        jButton11.setEnabled(false);

        javax.swing.GroupLayout liste_classesLayout = new javax.swing.GroupLayout(liste_classes);
        liste_classes.setLayout(liste_classesLayout);
        liste_classesLayout.setHorizontalGroup(
            liste_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_classesLayout.createSequentialGroup()
                .addGroup(liste_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(liste_classesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(liste_classesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton9)
                        .addGap(12, 12, 12)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)))
                .addGap(20, 20, 20))
        );
        liste_classesLayout.setVerticalGroup(
            liste_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_classesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(liste_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        theCard.add(liste_classes, "card_classe");

        table_salle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(table_salle);

        jButton16.setText("ajouter");
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("supprimer");
        jButton17.setEnabled(false);

        jButton18.setText("modifier");
        jButton18.setEnabled(false);

        javax.swing.GroupLayout liste_sallesLayout = new javax.swing.GroupLayout(liste_salles);
        liste_salles.setLayout(liste_sallesLayout);
        liste_sallesLayout.setHorizontalGroup(
            liste_sallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_sallesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(liste_sallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(liste_sallesLayout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addGap(12, 12, 12)
                        .addComponent(jButton18)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        liste_sallesLayout.setVerticalGroup(
            liste_sallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_sallesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(liste_sallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton18)
                    .addComponent(jButton17))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        theCard.add(liste_salles, "card_salle");

        liste_enseignant_bouton.setText("liste enseignants");
        liste_enseignant_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_enseignant_boutonActionPerformed(evt);
            }
        });

        Exit_button.setBackground(new java.awt.Color(200, 0, 0));
        Exit_button.setText("EXIT");
        Exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_buttonActionPerformed(evt);
            }
        });

        liste_matieres_bouton.setText("liste matiers");
        liste_matieres_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_matieres_boutonActionPerformed(evt);
            }
        });

        liste_classes_bouton.setText("liste classes");
        liste_classes_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_classes_boutonActionPerformed(evt);
            }
        });

        liste_salles_bouton.setText("liste salles");
        liste_salles_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_salles_boutonActionPerformed(evt);
            }
        });

        affecter_prof_classe.setText("affecter les prof au classes");
        affecter_prof_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affecter_prof_classeActionPerformed(evt);
            }
        });

        generer_emploi_du_temps.setText("generer emploi du temps");
        generer_emploi_du_temps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generer_emploi_du_tempsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(liste_enseignant_bouton)
                        .addGap(52, 52, 52)
                        .addComponent(liste_matieres_bouton)
                        .addGap(45, 45, 45)
                        .addComponent(liste_classes_bouton)
                        .addGap(39, 39, 39)
                        .addComponent(liste_salles_bouton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addComponent(theCard, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit_button)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(generer_emploi_du_temps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(affecter_prof_classe)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liste_enseignant_bouton)
                    .addComponent(liste_matieres_bouton)
                    .addComponent(liste_classes_bouton)
                    .addComponent(Exit_button)
                    .addComponent(liste_salles_bouton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(theCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affecter_prof_classe)
                    .addComponent(generer_emploi_du_temps))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit_buttonActionPerformed

    private void liste_enseignant_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_enseignant_boutonActionPerformed
      liste_enseignant.afficher();
    }//GEN-LAST:event_liste_enseignant_boutonActionPerformed
    
    private void liste_matieres_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_matieres_boutonActionPerformed
       liste_matieres.afficher();
    }//GEN-LAST:event_liste_matieres_boutonActionPerformed

    private void liste_classes_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_classes_boutonActionPerformed
       liste_classe.afficher();
    }//GEN-LAST:event_liste_classes_boutonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          ajout_classe.setVisible(true);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void table_classeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_classeMouseClicked
      jButton10.setEnabled(true);
       jButton11.setEnabled(true);
    }//GEN-LAST:event_table_classeMouseClicked

    private void table_enseignantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_enseignantMouseClicked
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
    }//GEN-LAST:event_table_enseignantMouseClicked

    private void Nom_enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_enseignantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_enseignantActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        ajout_enseignant.setVisible(false);
        Nom_enseignant.setText("");
        prenom_enseignant.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void liste_matiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_matiereMouseClicked
       
        
    }//GEN-LAST:event_liste_matiereMouseClicked

    private void liste_classesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_classesMouseClicked
        
        
    }//GEN-LAST:event_liste_classesMouseClicked

    private void table_matiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_matiereMouseClicked
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
    }//GEN-LAST:event_table_matiereMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    add_enseignant.ajouter();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
          ajout_classe.setVisible(false);
        Nom_classe.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      add_classe.ajouter();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void liste_salles_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_salles_boutonActionPerformed
    liste_salle.afficher();
    }//GEN-LAST:event_liste_salles_boutonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        ajout_salle.setVisible(true);
        Num_salle.setText("");
        designation_salle.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
     add_salle.ajouter();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void affecter_prof_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affecter_prof_classeActionPerformed
    affecter_prof_classes();      
    }//GEN-LAST:event_affecter_prof_classeActionPerformed

    private void NiveauItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NiveauItemStateChanged
        String niveau = Niveau.getSelectedItem().toString();
        String[] specialités = null;
        switch (niveau){
            case "1":
                 specialités = new String[]{"science","lettres"} ;
                 specialité.removeAllItems();
                 for(String item : specialités){
                 specialité.addItem(item);
                 }
                break;
            case "2":
                specialités = new String[]{"science experimental","lettres","math","tech_math"} ;
                 specialité.removeAllItems();
                 for(String item : specialités){
                 specialité.addItem(item);
                 }
                break;
            case "3":
                specialités = new String[]{"science experimental","lettres","math","tech_math"}  ;
                 specialité.removeAllItems();
                 for(String item : specialités){
                 specialité.addItem(item);
                 }
                break;
        }
    }//GEN-LAST:event_NiveauItemStateChanged

    private void specialitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialitéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialitéActionPerformed

    private void generer_emploi_du_tempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generer_emploi_du_tempsActionPerformed
        // TODO add your handling code here:
       generer_emploi.generer();
    }//GEN-LAST:event_generer_emploi_du_tempsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theMain().setVisible(true);
            }
        });

        try {
            connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/emploi_du_temp","root","midou");
 
        } catch (SQLException ex) {
            Logger.getLogger(theMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void affecter_prof_classes(){
    
      affecter_profs_classes.affecter_prof_classes();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton Exit_button;
    public static javax.swing.JComboBox<String> Niveau;
    public static javax.swing.JTextField Nom_classe;
    public static javax.swing.JTextField Nom_enseignant;
    public static javax.swing.JTextField Num_salle;
    private javax.swing.JButton affecter_prof_classe;
    public static javax.swing.JDialog ajout_classe;
    public static javax.swing.JDialog ajout_enseignant;
    public static javax.swing.JDialog ajout_salle;
    public static javax.swing.JTextField designation_salle;
    private javax.swing.JButton generer_emploi_du_temps;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton18;
    public static javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton20;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JPanel liste_classes;
    private javax.swing.JButton liste_classes_bouton;
    private javax.swing.JButton liste_enseignant_bouton;
    public static javax.swing.JPanel liste_enseignants;
    public static javax.swing.JPanel liste_matiere;
    private javax.swing.JButton liste_matieres_bouton;
    public static javax.swing.JPanel liste_salles;
    private javax.swing.JButton liste_salles_bouton;
    public static javax.swing.JComboBox<String> matiere_selection;
    public static javax.swing.JTextField prenom_enseignant;
    public static javax.swing.JComboBox<String> specialité;
    public static javax.swing.JTable table_classe;
    public static javax.swing.JTable table_enseignant;
    public static javax.swing.JTable table_matiere;
    public static javax.swing.JTable table_salle;
    public static javax.swing.JPanel theCard;
    // End of variables declaration//GEN-END:variables
}
